// NOTE: Under India Income Tax Act 2025 (effective 1 Apr 2026):
// Form 15CA is now Form 145 | Form 15CB is now Form 146
// Section 195 is now Section 397(3)(d)
// File on: incometax.gov.in → e-File → Income Tax Forms → Form 145

import { supabaseAdmin } from '../lib/supabaseServer.js';

// Form 145 XML generation (formerly 15CA)
export async function generateForm145Xml(
  transferId: string,
  part: 'A' | 'C',
  fields: Record<string, unknown>,
): Promise<string> {
  // TODO: Generate real Form 145 XML per IT portal schema (IT Act 2025)
  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Form 145 Part ${part} — Generated by REPAIHUB -->
<!-- Under Income Tax Act 2025 (formerly Form 15CA under IT Act 1961) -->
<!-- Transfer: ${transferId} -->
<Form145>
  <Part>${part}</Part>
  <TransferId>${transferId}</TransferId>
  <TaxActVersion>2025</TaxActVersion>
  <!-- TODO: Populate all required fields per IT portal Form 145 schema -->
</Form145>`;
  return xml;
}

export async function recordForm145Filing(
  transferId: string,
  form145Number: string,
): Promise<void> {
  // Write to both old and new column names during migration window
  await supabaseAdmin.from('transfers').update({
    form145_number: form145Number,
    fifteen_ca_number: form145Number, // backward compat pre-migration-016
    status: 'form145_filed',
  }).eq('id', transferId);
}

// Backward-compat aliases — remove after full migration
export const generate15CAXml = generateForm145Xml;
export const record15CAFiling = recordForm145Filing;
