// [GREEN] FifteenCAService — generates 15CA XML and tracks acknowledgements
// TODO: Implement 15CA XML generation when IT Portal integration is ready

import { supabaseAdmin } from '../lib/supabaseServer.js';

export async function generate15CAXml(
  transferId: string,
  part: 'A' | 'C',
  fields: Record<string, unknown>,
): Promise<string> {
  // TODO: Generate real 15CA XML per IT portal schema
  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- 15CA Part ${part} — Generated by REPAIHUB -->
<!-- Transfer: ${transferId} -->
<Form15CA>
  <Part>${part}</Part>
  <TransferId>${transferId}</TransferId>
  <!-- TODO: Populate all required fields from IT portal schema -->
</Form15CA>`;
  return xml;
}

export async function record15CAFiling(
  transferId: string,
  fifteenCANumber: string,
): Promise<void> {
  await supabaseAdmin.from('transfers').update({
    fifteen_ca_number: fifteenCANumber,
    status: '15ca_filed',
  }).eq('id', transferId);
}
